= Нововведения C++ 11-17
:revealjs_theme: white
:source-highlighter: highlightjs
:revealjs_hash: true
:icons: font

C++ часть 2, cеминар #4

ИТМО, 09.03.2020

== Recap предыдущего семинара

=== Не забывайте про const!

Если метод можно пометить как константный, это в 90% случаев стоит сделать.

=== Индексы vs итераторы

Итераторы зачастую более безопасно использовать, они могут предотвратить арифметические ошибки.

[source, cpp]
----
std::vector<int> vec;

int idx =
    std::lower_bound(begin(vec), end(vec), 10) - vec.begin();

if (idx != vec.size() && vec[idx] % 2 == 0) {
...
}
----

ifdef::backend-revealjs[=== !]

С итераторами запись будет более короткой, а вероятность ошибок меньше.

[source, cpp]
----
std::vector<int> vec;

auto it = std::lower_bound(begin(vec), end(vec), 10);

if (it != end(vec) && *it % 2 == 0) {
...
}
----

=== Оператор-мембер vs компаратор

Класс `Event` может требоваться упорядочить по разным полям в зависимости от ситуации.

[.step]
* В календаре -- по времени старта.
* В отчете -- по имени или количеству участников.
* На карте -- по номеру комнаты.

ifdef::backend-revealjs[=== !]

Вместо того, чтобы определять оператор `<` в классе `Event`, лучше
использовать компаратор с конкретной семантикой для конкретной ситуации.

Это делает код проще и локальнее (компаратор используется теми, кому он нужен).

== Есть ли вопросы по лекции?

== Задача 1 (1 балл)

Часто возникает задача сложить несколько строк между собой.

Использовать для этого оператор `+` неэффективно -- строка копируется много раз.

[source,cpp]
----
std::string username = "John";
std::string s =
    "hello " + username // аллокция 1
    + "!"; // аллокация 2
----

ifdef::backend-revealjs[=== !]

Реализуйте функцию `strcat`, умеющую конкатенировать строки за одну аллокацию (не считая аллокаций для вызова std::string).

[source,cpp]
----
std::string username = "John";
// одна аллокация
std::string s = cls_04::strcat("hello ", username, "!");
----

ifdef::backend-revealjs[=== !]

`strcat` должна уметь работать с `C-style` строками, `string`, `string_view` и числами.

[source,cpp]
----
std::string s = cls_04::strcat(1, " is less than ", 2.0);
// "1 is less than 2.000000"
----

ifdef::backend-revealjs[=== !]

В тесте есть дефайн `BENCHMARK`, который позволит сравнить между собой оператор `+` и `strcat`.


== Задача 2 (1 балл): constexpr-friendly optional

Вы уже наверняка знакомы с `std::optional`. Вам нужно написать свой вариант этого класса.

ifdef::backend-revealjs[=== !]

Пример использования.

[source,cpp]
----
constexpr optional<int> opt {20};
constexpr auto result = opt.value_or(10); // 20
----

