= My Vector <T>
:source-highlighter: highlightjs
:revealjs_hash: true
:icons: font

C++ часть 2, контрольная работа #1

ИТМО, 02.03.2020

== Задание

Вам необходимо написать класс, идентичный `std::vector<T>`.

ifdef::backend-revealjs[=== !]

Пожалуйста, обращайте внимание на noexcept
и гарантии исключений, мы будем это проверять.

Можно считать, что деструкторы классов, хранимых в векторе, noexcept.

== Задача №1 (1 балл)

Напишите базовую реализацию класса `control_01::vector`.

От класса требуется следующий функционал.

ifdef::backend-revealjs[=== !]

* Конструкторы/копирование
** По-умолчанию, copy/move конструкторы и операторы присваивания
* empty(), size(), capacity()
* front(), back(), operator[], at()
* push_back (для rvalue и lvalue)
* pop

Все методы должны удовлетворять строгой гарантии исключений.

== Задача №2 (+ 1 балл)

Добавьте в вектор следующие методы:

* reserve(new_capacity)
** После вызова capacity вектора должна стать >= переданной new_capacity
* erase(idx)
** Удаляет элемент на позиции, сдвигая все элементы перед ним

ifdef::backend-revealjs[=== !]

* emplace_back(args)
** Принимает аргументы, с помощью которых нужно сконструировать элемент в векторе

ifdef::backend-revealjs[=== !]

Обратите внимание:

* Методы reserve и erase теперь обязаны перемещать элементы вместо того,
чтобы копировать их, если есть возможность
* При этом должны соблюдаться гарантии исключений

== Задача 3 (+0.25 балла)

Добавьте в вектор конструктор, принимающий произвольное число элементов, и помещающий эти элементы в вектор.

Пример кода, который у вас должен скомпилироваться:

```c++
control_01::vector<std::string> vec {"hello", "world", "!"};
assert(vec.size() == 3 && vec[0] == "hello");
```

== Задача 4 (+0.75 балла)

Реализуйте для вашего вектора итераторы и методы `begin` и `end`. Достаточно константного итератора.

Пример кода, который должен у вас скомпилироваться:

```c++
control_01::vector<std::string> vec { "hello", "world", "!" };
std::for_each(
  std::make_reverse_iterator(std::end(vec)) + 1, 
  std::make_reverse_iterator(std::begin(vec)), 
  [](auto& elem) {
    std::cout << elem << std::endl;
  }
); // prints world hello
```
