= Двусторонняя очередь
:source-highlighter: highlightjs
:revealjs_hash: true
:icons: font
:customcss: https://codepen.io/anstreth/pen/WNvVedL.css
:revealjs_theme: white

C++ часть 2, контрольная работа #4

ИТМО, 18.05.2020

== Как сдавать контрольную

* Вы должны запушить ваше решение в ветку `sem_2_control_04`
* Не забудьте сделать PR и назначить ревьюера!

== Как запускать тесты

В файле `smoke.cpp` есть дифайны для каждого из заданий.

Чтобы активировать тесты, вам нужно раскомментировать дифайн.

== Описание задания

Вам нужно написать двустороннюю очередь фиксированного размера.

При конструировании очередь получает максимальный допустимый размер.

[.small-code]
[source,cpp]
----
deque<int> d { 5 }; // capacity == 5

d.emplace_back(1);
d.emplace_back(2);
d.emplace_back(3);

// size == 3
// content: [1, 2, 3]

d.emplace_front(4);
d.emplace_front(5);

// size == 5
// content: [5, 4, 1, 2, 3]

d.emplace_back(6);
d.emplace_back(7);
d.emplace_front(8);

// size == 5
// content: [8, 1, 2, 3, 6]
----

=== Требования к классу

* Сложность вставки/удаления элемента -- O(1).
* Очередь должна сделать только одну аллокацию при конструировании. Больше реаллокациий быть не должно.
* Если очередь заполнена, то:
** При `emplace_back(elem)`, `elem` затирает первый в очереди элемент.
** При `emplace_front(elem)`, `elem` затирает последний элемент.
* **При реализации нельзя пользоваться стандартными коллекциями.**

== Задача 1 (1 балл)

Напишите базовую версию класса `deque`.

Что требуется реализовать:

* Четыре конструктора/оператора копирования.
* Конструктор, принимающий `capacity` очереди.
* Методы `empty/size/capacity/operator[]`.
* Метод `emplace_back`.

=== Замечания

* Все методы должны соответствовать сильной гарантии исключений.
* Move-конструктор/оператор оставляет очередь в состоянии `capacity == 0`.

== Задача 2 (1 балл)

Добавьте следующие методы к вашей реализации:

* Метод `pop_back()`.
* Методы `emplace_front\pop_front`.

== Задача 3 (1 балл)

Добавьте метод `reverse`, который меняет порядок очереди на противоположный за O(1).

[NOTE]
`operator[]` должен работать за O(1).
